apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: descriptors.manifest.k8s.io
  annotations:
    displayName: Package Descriptor
    description: Represents an Package/Application metadata that could be installed in the cluster
spec:
  group: manifest.k8s.io
  version: v1alpha1
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      description: Represents a single version of the operator software
      required:
      - packageName
      - packageVersion
      - mediaType
      - description
      - packageOrg
      - content
      properties:
        content:
          size:
            type: integer
            description: content-size
          digest:
            type: string
            description: Sha256 digest of the content
          source:
            type: object
            description: Package content source
            oneOf:
            - type: object
              required:
                - blob
              properties:
                blob:
                  type: string
                  description: base64 of the tar.gz content
            - type: object
              required:
                - urls
              properties:
                urls:
                  type: array
                  description: List of mirrors to download the package
                  items:
                    type: string
                    description: Download url
        appName:
          type: string
          description: name of the packaged application
        mediaType:
          type: string
          description: the package format
          default: kubernetes
        packageOrg:
          type: string
          description: Package organization
        description:
          type: string
          description: Description of what the application does
        keywords:
          default: []
          type: array
          description: List of keywords which will be used to discover and categorize app types
          items:
            type: string
        icon:
          type: string
          description: An pointer to the icon.
        packageVersion:
          type: string
          description: Version of the package, semver
          pattern: ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$

  names:
    plural: packages
    singular: package
    kind: Package
    listKind: PackageList
